[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ops-scenario"

# this needs to MATCH EXACTLY the tag name for the publish pipeline to activate.
version = "2.0.0"
authors = [
    { name = "Pietro Pasotti", email = "pietro.pasotti@canonical.com" }
]
description = "Python library providing a Scenario-based testing API for Operator Framework charms."
license.text = "Apache-2.0"
keywords = ["juju", "test"]

dependencies = ["ops>=2.0"]
readme = "README.md"
requires-python = ">=3.8"

classifiers = [
    "Development Status :: 3 - Alpha",
    "Topic :: Utilities",
    "License :: OSI Approved :: Apache Software License",
]


[project.urls]
"Homepage" = "https://github.com/PietroPasotti/ops-scenario"
"Bug Tracker" = "https://github.com/PietroPasotti/ops-scenario/issues"


[tool.setuptools.package-dir]
scenario = "scenario"


[tool.black]
include = '\.pyi?$'


[tool.isort]
profile = "black"

[bdist_wheel]
universal=1
